name=BuzzerMusic
version=1.1.0
author=Pablo Gonzalez <pabgonza@gmail.com>
maintainer=Pablo Gonzalez <pabgonza@gmail.com>
sentence=Canciones listas para tocar con un buzzer.
paragraph=Melodias clasicas (Star Wars, Mario Bros, Happy Birthday, Himno de la Alegria) para buzzer pasivo usando tone(). Pensada para cursos de Arduino para ninos.
category=Signal Input/Output
url=https://github.com/pabgonza/BuzzerMusic
architectures=*
